/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Pranjal
 */
public class ChooseType extends javax.swing.JFrame {

    /**
     * Creates new form ChooseType
     */
    public ChooseType() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChooseTypePanel = new javax.swing.JPanel();
        BtnPanel = new javax.swing.JPanel();
        CTBtn = new javax.swing.JButton();
        PTButton = new javax.swing.JButton();
        ChooseTypeLabel = new javax.swing.JLabel();
        BackBTn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ChooseTypePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ChooseTypePanel.setLayout(null);

        CTBtn.setBackground(new java.awt.Color(147, 252, 251));
        CTBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CTBtn.setText("CURRENT TRANSFORMER (CT)");
        CTBtn.setBorder(new javax.swing.border.MatteBorder(null));
        CTBtn.setMaximumSize(new java.awt.Dimension(288, 23));
        CTBtn.setMinimumSize(new java.awt.Dimension(288, 23));
        CTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTBtnActionPerformed(evt);
            }
        });

        PTButton.setBackground(new java.awt.Color(147, 252, 251));
        PTButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PTButton.setText("POTENTIAL TRANSFORMER (PT)");
        PTButton.setBorder(new javax.swing.border.MatteBorder(null));
        PTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BtnPanelLayout = new javax.swing.GroupLayout(BtnPanel);
        BtnPanel.setLayout(BtnPanelLayout);
        BtnPanelLayout.setHorizontalGroup(
            BtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnPanelLayout.createSequentialGroup()
                .addComponent(CTBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(PTButton, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        BtnPanelLayout.setVerticalGroup(
            BtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnPanelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(BtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CTBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PTButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        ChooseTypePanel.add(BtnPanel);
        BtnPanel.setBounds(101, 175, 939, 498);

        ChooseTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ChooseTypeLabel.setText("     CHOOSE TYPE");
        ChooseTypeLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ChooseTypeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ChooseTypePanel.add(ChooseTypeLabel);
        ChooseTypeLabel.setBounds(340, 80, 350, 89);

        BackBTn.setBackground(new java.awt.Color(255, 255, 204));
        BackBTn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BackBTn.setText("BACK");
        BackBTn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BackBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTnActionPerformed(evt);
            }
        });
        ChooseTypePanel.add(BackBTn);
        BackBTn.setBounds(820, 100, 99, 45);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChooseTypePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ChooseTypePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1034, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new InputCT().setVisible(true);
    }//GEN-LAST:event_CTBtnActionPerformed

    private void PTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new InputPT().setVisible(true);
    }//GEN-LAST:event_PTButtonActionPerformed

    private void BackBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_BackBTnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTn;
    private javax.swing.JPanel BtnPanel;
    private javax.swing.JButton CTBtn;
    private javax.swing.JLabel ChooseTypeLabel;
    private javax.swing.JPanel ChooseTypePanel;
    private javax.swing.JButton PTButton;
    // End of variables declaration//GEN-END:variables
}
