/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Pranjal
 */
public class PTPage extends javax.swing.JFrame {

    /**
     * Creates new form PTPage
     */
    public PTPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanelInputPT = new javax.swing.JPanel();
        InputPanelPT = new javax.swing.JPanel();
        InputLabelPT = new javax.swing.JLabel();
        InputVariablePanelPT = new javax.swing.JPanel();
        RatioLabelPT = new javax.swing.JLabel();
        BurdenLabelPT = new javax.swing.JLabel();
        BurdenDropDownPT = new javax.swing.JComboBox<>();
        CoreSizeLabelPT = new javax.swing.JLabel();
        CoreSizeDropDownPT = new javax.swing.JComboBox<>();
        VoltageFactorLabel = new javax.swing.JLabel();
        VoltFactorDropDown = new javax.swing.JComboBox<>();
        CTRatioLabelPT = new javax.swing.JLabel();
        CTRatioTxtField1PT = new javax.swing.JTextField();
        CTRatioTxtField2PT = new javax.swing.JTextField();
        jLabel1PT = new javax.swing.JLabel();
        EpoxyRadioButtonPT = new javax.swing.JRadioButton();
        OilCooledRadioButtonPT = new javax.swing.JRadioButton();
        STCLabelPT = new javax.swing.JLabel();
        STCDropDownPT = new javax.swing.JComboBox<>();
        LogoutBtnPT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SidePanelInputPT.setBackground(new java.awt.Color(0, 204, 255));
        SidePanelInputPT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout SidePanelInputPTLayout = new javax.swing.GroupLayout(SidePanelInputPT);
        SidePanelInputPT.setLayout(SidePanelInputPTLayout);
        SidePanelInputPTLayout.setHorizontalGroup(
            SidePanelInputPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
        SidePanelInputPTLayout.setVerticalGroup(
            SidePanelInputPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        InputPanelPT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        InputLabelPT.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        InputLabelPT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InputLabelPT.setText("INPUTS FOR PT");
        InputLabelPT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        InputLabelPT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        RatioLabelPT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RatioLabelPT.setText("Type                    :");

        BurdenLabelPT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BurdenLabelPT.setText("Burden                :");

        BurdenDropDownPT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CoreSizeLabelPT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CoreSizeLabelPT.setText("Voltage Rating    :");

        CoreSizeDropDownPT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        VoltageFactorLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        VoltageFactorLabel.setText("Voltage Factor    :");

        VoltFactorDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CTRatioLabelPT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CTRatioLabelPT.setText("CT Ratio              :");

        CTRatioTxtField1PT.setText("Ratio 1");

        CTRatioTxtField2PT.setText("jTextField2");

        jLabel1PT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1PT.setText("/");

        EpoxyRadioButtonPT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EpoxyRadioButtonPT.setText("Epoxy / Dry");
        EpoxyRadioButtonPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EpoxyRadioButtonPTActionPerformed(evt);
            }
        });

        OilCooledRadioButtonPT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        OilCooledRadioButtonPT.setText("Oil Cooled");

        STCLabelPT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        STCLabelPT.setText("Current Density   :");

        STCDropDownPT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        STCDropDownPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STCDropDownPTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InputVariablePanelPTLayout = new javax.swing.GroupLayout(InputVariablePanelPT);
        InputVariablePanelPT.setLayout(InputVariablePanelPTLayout);
        InputVariablePanelPTLayout.setHorizontalGroup(
            InputVariablePanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputVariablePanelPTLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(InputVariablePanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VoltageFactorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RatioLabelPT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BurdenLabelPT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CoreSizeLabelPT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CTRatioLabelPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(STCLabelPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(InputVariablePanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputVariablePanelPTLayout.createSequentialGroup()
                        .addGroup(InputVariablePanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(VoltFactorDropDown, javax.swing.GroupLayout.Alignment.LEADING, 0, 176, Short.MAX_VALUE)
                            .addComponent(BurdenDropDownPT, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CoreSizeDropDownPT, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(InputVariablePanelPTLayout.createSequentialGroup()
                        .addComponent(EpoxyRadioButtonPT, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OilCooledRadioButtonPT)
                        .addGap(54, 54, 54))
                    .addGroup(InputVariablePanelPTLayout.createSequentialGroup()
                        .addGroup(InputVariablePanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InputVariablePanelPTLayout.createSequentialGroup()
                                .addComponent(CTRatioTxtField1PT, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1PT, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CTRatioTxtField2PT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(STCDropDownPT, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 112, Short.MAX_VALUE))))
        );
        InputVariablePanelPTLayout.setVerticalGroup(
            InputVariablePanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputVariablePanelPTLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(InputVariablePanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RatioLabelPT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EpoxyRadioButtonPT)
                    .addComponent(OilCooledRadioButtonPT))
                .addGap(18, 18, 18)
                .addGroup(InputVariablePanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputVariablePanelPTLayout.createSequentialGroup()
                        .addComponent(BurdenDropDownPT)
                        .addGap(1, 1, 1))
                    .addComponent(BurdenLabelPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(InputVariablePanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CoreSizeLabelPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(InputVariablePanelPTLayout.createSequentialGroup()
                        .addComponent(CoreSizeDropDownPT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addGroup(InputVariablePanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(VoltageFactorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(InputVariablePanelPTLayout.createSequentialGroup()
                        .addComponent(VoltFactorDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addGroup(InputVariablePanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InputVariablePanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CTRatioLabelPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1PT)
                        .addComponent(CTRatioTxtField2PT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE))
                    .addGroup(InputVariablePanelPTLayout.createSequentialGroup()
                        .addComponent(CTRatioTxtField1PT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addGroup(InputVariablePanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(STCLabelPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(InputVariablePanelPTLayout.createSequentialGroup()
                        .addComponent(STCDropDownPT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(52, 52, 52))
        );

        LogoutBtnPT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LogoutBtnPT.setText("Log Out");
        LogoutBtnPT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogoutBtnPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnPTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InputPanelPTLayout = new javax.swing.GroupLayout(InputPanelPT);
        InputPanelPT.setLayout(InputPanelPTLayout);
        InputPanelPTLayout.setHorizontalGroup(
            InputPanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputPanelPTLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(InputPanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputVariablePanelPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InputPanelPTLayout.createSequentialGroup()
                        .addComponent(InputLabelPT, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LogoutBtnPT)))
                .addGap(22, 22, 22))
        );
        InputPanelPTLayout.setVerticalGroup(
            InputPanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelPTLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(InputPanelPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputLabelPT)
                    .addComponent(LogoutBtnPT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(InputVariablePanelPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SidePanelInputPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputPanelPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SidePanelInputPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(InputPanelPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EpoxyRadioButtonPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EpoxyRadioButtonPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EpoxyRadioButtonPTActionPerformed

    private void LogoutBtnPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnPTActionPerformed
        // TODO add your handling code here:
        new NewJFrame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_LogoutBtnPTActionPerformed

    private void STCDropDownPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STCDropDownPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STCDropDownPTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PTPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PTPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PTPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PTPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PTPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BurdenDropDownPT;
    private javax.swing.JLabel BurdenLabelPT;
    private javax.swing.JLabel CTRatioLabelPT;
    private javax.swing.JTextField CTRatioTxtField1PT;
    private javax.swing.JTextField CTRatioTxtField2PT;
    private javax.swing.JComboBox<String> CoreSizeDropDownPT;
    private javax.swing.JLabel CoreSizeLabelPT;
    private javax.swing.JRadioButton EpoxyRadioButtonPT;
    private javax.swing.JLabel InputLabelPT;
    private javax.swing.JPanel InputPanelPT;
    private javax.swing.JPanel InputVariablePanelPT;
    private javax.swing.JButton LogoutBtnPT;
    private javax.swing.JRadioButton OilCooledRadioButtonPT;
    private javax.swing.JLabel RatioLabelPT;
    private javax.swing.JComboBox<String> STCDropDownPT;
    private javax.swing.JLabel STCLabelPT;
    private javax.swing.JPanel SidePanelInputPT;
    private javax.swing.JComboBox<String> VoltFactorDropDown;
    private javax.swing.JLabel VoltageFactorLabel;
    private javax.swing.JLabel jLabel1PT;
    // End of variables declaration//GEN-END:variables
}
